package org.example;

public enum ProductCategory {
    test_category1,
    test_category2,
    test_category3,
    akcesoria_plastikowe_kostki_do_gry_ekstra,
    akcesoria_plastikowe_kostki_do_gry_zwykłe,
    gamebook,
    gry_dla_dzieci_edukacyjne,
    gry_dla_dzieci_inne,
    gry_dla_dzieci_karciane,
    gry_dla_dzieci_planszowe,
    gry_dla_dzieci_quizy_i_loteryjki,
    gry_karciane_akcesoria_do_kart,
    gry_karciane_dla_dzieci,
    gry_karciane_imprezowe,
    gry_karciane_kooperacyjne,
    gry_karciane_logiczne,
    gry_karciane_przygodowe,
    gry_karciane_rodzinne,
    gry_karciane_strategiczne,
    gry_planszowe_akcesoria,
    gry_planszowe_ekonomiczne,
    gry_planszowe_imprezowe,
    gry_planszowe_klasyczne,
    gry_planszowe_kooperacyjne,
    gry_planszowe_kościane,
    gry_planszowe_przygodowe,
    gry_planszowe_rodzinne,
    gry_planszowe_strategiczne,
    łamigłówki_Huzzle_Cast,
    łamigłówki_kostka_GAN,
    łamigłówki_zwariowane,
    puzzle_dla_dorosłych,
    puzzle_dla_dzieci;
    }
